package com.example.data.api

import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.net.Uri
import android.util.Base64
import com.example.BuildConfig
import com.example.data.model.ImageAspectRatio
import com.squareup.moshi.Moshi
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.delay
import kotlinx.coroutines.withContext
import okhttp3.OkHttpClient
import okhttp3.logging.HttpLoggingInterceptor
import retrofit2.Response
import retrofit2.Retrofit
import retrofit2.converter.moshi.MoshiConverterFactory
import retrofit2.http.Body
import retrofit2.http.POST
import retrofit2.http.Path
import retrofit2.http.Query
import java.io.ByteArrayOutputStream
import java.io.InputStream
import java.net.URLEncoder
import java.util.concurrent.TimeUnit
import kotlin.random.Random

interface GeminiApi {
    @POST("v1beta/models/{model}:generateContent")
    suspend fun generateContent(
        @Path("model") model: String,
        @Query("key") apiKey: String,
        @Body request: GeminiGenerateRequest
    ): Response<GeminiGenerateResponse>
}

object GeminiApiClient {
    private const val BASE_URL = "https://generativelanguage.googleapis.com/"

    private val moshi = Moshi.Builder()
        .add(KotlinJsonAdapterFactory())
        .build()

    private val okHttpClient = OkHttpClient.Builder()
        .connectTimeout(60, TimeUnit.SECONDS)
        .readTimeout(60, TimeUnit.SECONDS)
        .writeTimeout(60, TimeUnit.SECONDS)
        .addInterceptor(HttpLoggingInterceptor().apply {
            level = HttpLoggingInterceptor.Level.BASIC
        })
        .build()

    val api: GeminiApi by lazy {
        Retrofit.Builder()
            .baseUrl(BASE_URL)
            .client(okHttpClient)
            .addConverterFactory(MoshiConverterFactory.create(moshi))
            .build()
            .create(GeminiApi::class.java)
    }

    suspend fun executeGenerateContent(
        modelName: String,
        history: List<GeminiContent>,
        systemInstruction: String = "You are RAKIB AI, the most advanced, powerful, and helpful AI assistant. You must always provide 100% correct, factual, and highly accurate answers to everything the user asks. If the user attaches images, documents, or videos, analyze them with deep insight. Format your responses with beautiful Markdown styling.",
        customApiKey: String? = null
    ): Result<String> = withContext(Dispatchers.IO) {
        val apiKey = when {
            !customApiKey.isNullOrBlank() -> customApiKey.trim()
            BuildConfig.GEMINI_API_KEY.isNotBlank() && BuildConfig.GEMINI_API_KEY != "MY_GEMINI_API_KEY" -> BuildConfig.GEMINI_API_KEY
            else -> ""
        }

        if (apiKey.isBlank()) {
            return@withContext Result.failure(
                Exception("Gemini API key is not configured. Tap the 🔑 Key button in the top bar to enter your free Gemini API key.")
            )
        }

        val request = GeminiGenerateRequest(
            contents = history,
            systemInstruction = GeminiContent(
                parts = listOf(GeminiPart(text = systemInstruction))
            )
        )

        // Retry mechanism for transient 503 errors
        var lastException: Exception? = null
        for (attempt in 0..3) {
            try {
                val response = api.generateContent(
                    model = modelName,
                    apiKey = apiKey,
                    request = request
                )

                if (response.isSuccessful && response.body() != null) {
                    val body = response.body()!!
                    val candidateText = body.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text
                    if (!candidateText.isNullOrBlank()) {
                        return@withContext Result.success(candidateText)
                    } else if (body.error != null) {
                        return@withContext Result.failure(
                            Exception(body.error.message ?: "Unknown API error occurred.")
                        )
                    } else {
                        return@withContext Result.failure(
                            Exception("No response text generated by AI model.")
                        )
                    }
                } else {
                    val errorBodyStr = response.errorBody()?.string() ?: ""
                    val code = response.code()
                    if (code == 503 && attempt < 3) {
                        delay(2000L * (attempt + 1))
                        continue
                    }
                    return@withContext Result.failure(
                        Exception("API Error ($code): ${if (errorBodyStr.isNotBlank()) errorBodyStr else response.message()}")
                    )
                }
            } catch (e: Exception) {
                lastException = e
                if (attempt < 3) {
                    delay(2000L * (attempt + 1))
                }
            }
        }

        return@withContext Result.failure(
            lastException ?: Exception("Network error connecting to Gemini AI servers.")
        )
    }

    /**
     * Builds an AI generated image URL with prompt enhancement and selected aspect ratio
     */
    fun buildPictureAiUrl(prompt: String, ratio: ImageAspectRatio): String {
        var basePrompt = prompt.trim()
        if (basePrompt.equals("bmw", ignoreCase = true)) {
            basePrompt = "A stunning, highly modified BMW M5, black aggressive look, neon street lights reflection, cinematic shot"
        } else if (basePrompt.contains("bmw", ignoreCase = true)) {
            basePrompt = basePrompt.replace("bmw", "beautiful BMW M5", ignoreCase = true)
        }

        val enhanced = "$basePrompt, masterpiece, best quality, ultra-detailed, sharp focus, stunning color combination, perfect composition, vibrant colors, cinematic lighting, photorealistic"
        val encodedPrompt = URLEncoder.encode(enhanced, "UTF-8")
        val seed = Random.nextInt(1000000, 99999999)

        return "https://image.pollinations.ai/prompt/$encodedPrompt?seed=$seed&width=${ratio.width}&height=${ratio.height}&nologo=true&enhance=true&safe=true"
    }

    /**
     * Helper to read Uri content and convert to Base64
     */
    suspend fun uriToBase64(context: Context, uri: Uri, mimeType: String): String? = withContext(Dispatchers.IO) {
        try {
            if (mimeType.startsWith("image/")) {
                val inputStream: InputStream? = context.contentResolver.openInputStream(uri)
                val originalBitmap = BitmapFactory.decodeStream(inputStream)
                inputStream?.close()

                if (originalBitmap != null) {
                    // Downscale large bitmaps to maintain performance and avoid payload limits
                    val maxDimension = 1536
                    val scaledBitmap = if (originalBitmap.width > maxDimension || originalBitmap.height > maxDimension) {
                        val ratio = originalBitmap.width.toFloat() / originalBitmap.height.toFloat()
                        val newWidth = if (ratio > 1) maxDimension else (maxDimension * ratio).toInt()
                        val newHeight = if (ratio > 1) (maxDimension / ratio).toInt() else maxDimension
                        Bitmap.createScaledBitmap(originalBitmap, newWidth, newHeight, true)
                    } else {
                        originalBitmap
                    }

                    val outputStream = ByteArrayOutputStream()
                    scaledBitmap.compress(Bitmap.CompressFormat.JPEG, 85, outputStream)
                    val byteArray = outputStream.toByteArray()
                    return@withContext Base64.encodeToString(byteArray, Base64.NO_WRAP)
                }
            } else {
                val inputStream = context.contentResolver.openInputStream(uri)
                val bytes = inputStream?.readBytes()
                inputStream?.close()
                if (bytes != null) {
                    return@withContext Base64.encodeToString(bytes, Base64.NO_WRAP)
                }
            }
        } catch (e: Exception) {
            e.printStackTrace()
        }
        null
    }
}
